### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by violencia** [fogleman/xy#1]
Hi, Michael. 

Could you add some instructions on how to install and use your code, please?

What I've done so far (without luck) is:
1. I uploaded firmware.ino to my plotter (Orion based)
2. Run `python test.py`

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import xy
  File "/Users/violeta/fogleman/xy/__init__.py", line 5, in <module>
    from gcode import GCode
ImportError: No module named gcode
```

**Comment by fogleman** [comment]
That error is from some old code that was hanging around. I fixed it.

Also added a README with a few more instructions.

**Comment by fogleman** [comment]
Let me know what else you run into and I can help.
